---
# Not needed since ansible already has them
#- name: create vars
#  command: hostname
#  register: hostname

- name: install mariadb
  yum:
    name: mariadb
    state: present
    
- name: Get values for some values
  template:
   src=mycoolconfig.j2
   dest=/home/vagrant/config.ch
